-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS hackmate.role (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL
);

INSERT INTO hackmate.role (name) VALUES
 ('Fullstack'),
 ('Frontend'),
 ('Backend'),
 ('UX/UI Designer'),
 ('Product Designer'),
 ('Project Manager'),
 ('Analyst'),
 ('ML'),
 ('Data Scientist'),
 ('Mobile Developer');


CREATE TABLE IF NOT EXISTS hackmate.skill (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL
);

INSERT INTO hackmate.skill (name) VALUES
('HTML'),
('HTML5'),
('CSS'),
('CSS3'),
('SCSS'),
('SASS'),
('LESS'),
('JavaScript'),
('TypeScript'),
('React'),
('React Hooks'),
('React Query'),
('Next.js'),
('Remix'),
('Vue.js'),
('Vuex'),
('Pinia'),
('Nuxt.js'),
('Angular'),
('RxJS'),
('Svelte'),
('SvelteKit'),
('SolidJS'),
('Alpine.js'),
('jQuery'),
('Bootstrap'),
('Tailwind CSS'),
('Material UI'),
('Ant Design'),
('Chakra UI'),
('ShadCN'),
('Radix UI'),
('Emotion'),
('Styled Components'),
('Storybook'),
('Webpack'),
('Vite'),
('Rollup'),
('Parcel'),
('Babel'),
('ESLint'),
('Prettier'),
('Redux'),
('Redux Toolkit'),
('Zustand'),
('MobX'),
('Recoil'),
('Jotai'),
('Framer Motion'),
('GSAP'),
('Three.js'),
('WebGL'),
('Canvas API'),
('Chart.js'),
('ECharts'),
('D3.js'),
('WebSockets'),
('WebRTC'),
('Progressive Web Apps'),
('Service Workers'),
('SEO'),
('Accessibility'),
('Responsive Design'),
('Mobile-first'),
('SSR'),
('SSG'),
('CSR'),
('Microfrontends'),
('Node.js'),
('Express.js'),
('NestJS'),
('Koa'),
('Hapi'),
('Fastify'),
('Meteor'),
('GraphQL'),
('Apollo Server'),
('REST API'),
('tRPC'),
('Python'),
('Django'),
('Django REST Framework'),
('Flask'),
('FastAPI'),
('Bottle'),
('Tornado'),
('SQLAlchemy'),
('Pydantic'),
('Jinja2'),
('Java'),
('Spring Framework'),
('Spring Boot'),
('Hibernate'),
('Maven'),
('Gradle'),
('Kotlin'),
('Ktor'),
('Scala'),
('Play Framework'),
('C#'),
('.NET'),
('ASP.NET Core'),
('Entity Framework'),
('F#'),
('Go'),
('Gin'),
('Echo'),
('Revel'),
('Rust'),
('Actix Web'),
('Rocket'),
('C++'),
('Qt'),
('Boost'),
('C'),
('PHP'),
('Laravel'),
('Symfony'),
('CodeIgniter'),
('Yii2'),
('Ruby'),
('Ruby on Rails'),
('Sinatra'),
('Elixir'),
('Phoenix'),
('Erlang'),
('Haskell'),
('OCaml'),
('R'),
('MATLAB'),
('Julia'),
('MySQL'),
('PostgreSQL'),
('SQLite'),
('SQL Server'),
('MariaDB'),
('MongoDB'),
('Redis'),
('DynamoDB'),
('Cassandra'),
('CouchDB'),
('Firestore'),
('Firebase RTDB'),
('Supabase'),
('FaunaDB'),
('Neo4j'),
('InfluxDB'),
('TimescaleDB'),
('ElasticSearch'),
('OpenSearch'),
('Meilisearch'),
('ClickHouse'),
('BigQuery'),
('Snowflake'),
('Presto'),
('Hive'),
('Kafka'),
('RabbitMQ'),
('ActiveMQ'),
('NATS'),
('MQTT'),
('ZeroMQ'),
('Celery'),
('Redis Queue'),
('BullMQ'),
('AWS'),
('AWS S3'),
('AWS Lambda'),
('AWS EC2'),
('AWS ECS'),
('AWS EKS'),
('AWS RDS'),
('AWS DynamoDB'),
('AWS API Gateway'),
('AWS CloudFront'),
('AWS Cognito'),
('AWS SNS'),
('AWS SQS'),
('AWS CloudWatch'),
('GCP'),
('GCP Cloud Run'),
('GCP Functions'),
('Firebase'),
('Azure'),
('Azure Functions'),
('Vercel'),
('Netlify'),
('Cloudflare Workers'),
('Docker'),
('Docker Compose'),
('Kubernetes'),
('Helm'),
('Terraform'),
('Ansible'),
('Pulumi'),
('Jenkins'),
('GitHub Actions'),
('GitLab CI/CD'),
('CircleCI'),
('Travis CI'),
('ArgoCD'),
('Nginx'),
('Apache'),
('Caddy'),
('Load Balancing'),
('Reverse Proxy'),
('Linux'),
('Ubuntu'),
('Debian'),
('CentOS'),
('Alpine Linux'),
('Bash'),
('Zsh'),
('Shell scripting'),
('Security'),
('OAuth2'),
('OpenID Connect'),
('JWT'),
('SSO'),
('TLS'),
('HTTPS'),
('Penetration Testing'),
('OWASP'),
('Web Security'),
('SQL Injection Prevention'),
('XSS Prevention'),
('CSRF Protection'),
('Input Validation'),
('Rate Limiting'),
('Logging'),
('Monitoring'),
('Prometheus'),
('Grafana'),
('Loki'),
('ELK Stack'),
('Jaeger'),
('OpenTelemetry'),
('Error Tracking'),
('Sentry'),
('DataDog'),
('New Relic'),
('Mobile Development'),
('Kotlin Android'),
('Java Android'),
('Jetpack Compose'),
('XML Layouts'),
('Android Studio'),
('ADB'),
('Swift'),
('SwiftUI'),
('UIKit'),
('iOS Development'),
('Xcode'),
('Objective-C'),
('Flutter'),
('Dart'),
('React Native'),
('Xamarin'),
('Ionic'),
('Capacitor'),
('Unity'),
('Unreal Engine'),
('Godot'),
('Cocos2d-x'),
('GameMaker'),
('VR/AR'),
('ARCore'),
('ARKit'),
('OpenXR'),
('Three.js WebXR'),
('Machine Learning'),
('AI'),
('Deep Learning'),
('TensorFlow'),
('PyTorch'),
('Keras');

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS hackmate.role;
DROP TABLE IF EXISTS hackmate.skill;
-- +goose StatementEnd
