// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostApiAdminHacksWithBody request with any body
	PostApiAdminHacksWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiAdminHacks(ctx context.Context, body PostApiAdminHacksJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiAdminLoginWithBody request with any body
	PostApiAdminLoginWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiAdminLogin(ctx context.Context, body PostApiAdminLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiHacks request
	GetApiHacks(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiHacksHackId request
	GetApiHacksHackId(ctx context.Context, hackId int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiHacksHackIdEnterWithBody request with any body
	PostApiHacksHackIdEnterWithBody(ctx context.Context, hackId int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiHacksHackIdEnter(ctx context.Context, hackId int, body PostApiHacksHackIdEnterJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiHacksHackIdInvitations request
	GetApiHacksHackIdInvitations(ctx context.Context, hackId int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiHacksHackIdInvitationsInviteIdAccept request
	GetApiHacksHackIdInvitationsInviteIdAccept(ctx context.Context, hackId int, inviteId int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiHacksHackIdParticipants request
	GetApiHacksHackIdParticipants(ctx context.Context, hackId int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiHacksHackIdParticipantsParticipantId request
	GetApiHacksHackIdParticipantsParticipantId(ctx context.Context, hackId int, participantId int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiHacksHackIdParticipantsParticipantsIdInvite request
	PostApiHacksHackIdParticipantsParticipantsIdInvite(ctx context.Context, hackId int, participantsId int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiHacksHackIdRequests request
	GetApiHacksHackIdRequests(ctx context.Context, hackId int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiHacksHackIdRequestsRequestIdAccept request
	PostApiHacksHackIdRequestsRequestIdAccept(ctx context.Context, hackId int, requestId int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiHacksHackIdTeams request
	GetApiHacksHackIdTeams(ctx context.Context, hackId int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiHacksHackIdTeamsWithBody request with any body
	PostApiHacksHackIdTeamsWithBody(ctx context.Context, hackId int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiHacksHackIdTeams(ctx context.Context, hackId int, body PostApiHacksHackIdTeamsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiHacksHackIdTeamsTeamId request
	GetApiHacksHackIdTeamsTeamId(ctx context.Context, hackId int, teamId int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiHacksHackIdTeamsTeamIdRequest request
	PostApiHacksHackIdTeamsTeamIdRequest(ctx context.Context, hackId int, teamId int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiHealthcheсk request
	GetApiHealthcheсk(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiLoginWithBody request with any body
	PostApiLoginWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiLogin(ctx context.Context, body PostApiLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiRoles request
	GetApiRoles(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiSkills request
	GetApiSkills(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiUser request
	GetApiUser(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiUsersUserId request
	GetApiUsersUserId(ctx context.Context, userId int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiUsersUserIdTeams request
	GetApiUsersUserIdTeams(ctx context.Context, userId int, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostApiAdminHacksWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiAdminHacksRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiAdminHacks(ctx context.Context, body PostApiAdminHacksJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiAdminHacksRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiAdminLoginWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiAdminLoginRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiAdminLogin(ctx context.Context, body PostApiAdminLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiAdminLoginRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiHacks(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiHacksRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiHacksHackId(ctx context.Context, hackId int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiHacksHackIdRequest(c.Server, hackId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiHacksHackIdEnterWithBody(ctx context.Context, hackId int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiHacksHackIdEnterRequestWithBody(c.Server, hackId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiHacksHackIdEnter(ctx context.Context, hackId int, body PostApiHacksHackIdEnterJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiHacksHackIdEnterRequest(c.Server, hackId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiHacksHackIdInvitations(ctx context.Context, hackId int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiHacksHackIdInvitationsRequest(c.Server, hackId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiHacksHackIdInvitationsInviteIdAccept(ctx context.Context, hackId int, inviteId int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiHacksHackIdInvitationsInviteIdAcceptRequest(c.Server, hackId, inviteId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiHacksHackIdParticipants(ctx context.Context, hackId int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiHacksHackIdParticipantsRequest(c.Server, hackId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiHacksHackIdParticipantsParticipantId(ctx context.Context, hackId int, participantId int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiHacksHackIdParticipantsParticipantIdRequest(c.Server, hackId, participantId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiHacksHackIdParticipantsParticipantsIdInvite(ctx context.Context, hackId int, participantsId int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiHacksHackIdParticipantsParticipantsIdInviteRequest(c.Server, hackId, participantsId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiHacksHackIdRequests(ctx context.Context, hackId int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiHacksHackIdRequestsRequest(c.Server, hackId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiHacksHackIdRequestsRequestIdAccept(ctx context.Context, hackId int, requestId int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiHacksHackIdRequestsRequestIdAcceptRequest(c.Server, hackId, requestId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiHacksHackIdTeams(ctx context.Context, hackId int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiHacksHackIdTeamsRequest(c.Server, hackId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiHacksHackIdTeamsWithBody(ctx context.Context, hackId int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiHacksHackIdTeamsRequestWithBody(c.Server, hackId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiHacksHackIdTeams(ctx context.Context, hackId int, body PostApiHacksHackIdTeamsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiHacksHackIdTeamsRequest(c.Server, hackId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiHacksHackIdTeamsTeamId(ctx context.Context, hackId int, teamId int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiHacksHackIdTeamsTeamIdRequest(c.Server, hackId, teamId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiHacksHackIdTeamsTeamIdRequest(ctx context.Context, hackId int, teamId int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiHacksHackIdTeamsTeamIdRequestRequest(c.Server, hackId, teamId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiHealthcheсk(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiHealthcheсkRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiLoginWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiLoginRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiLogin(ctx context.Context, body PostApiLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiLoginRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiRoles(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiRolesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiSkills(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiSkillsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiUser(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiUserRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiUsersUserId(ctx context.Context, userId int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiUsersUserIdRequest(c.Server, userId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiUsersUserIdTeams(ctx context.Context, userId int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiUsersUserIdTeamsRequest(c.Server, userId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostApiAdminHacksRequest calls the generic PostApiAdminHacks builder with application/json body
func NewPostApiAdminHacksRequest(server string, body PostApiAdminHacksJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiAdminHacksRequestWithBody(server, "application/json", bodyReader)
}

// NewPostApiAdminHacksRequestWithBody generates requests for PostApiAdminHacks with any type of body
func NewPostApiAdminHacksRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/admin/hacks")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostApiAdminLoginRequest calls the generic PostApiAdminLogin builder with application/json body
func NewPostApiAdminLoginRequest(server string, body PostApiAdminLoginJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiAdminLoginRequestWithBody(server, "application/json", bodyReader)
}

// NewPostApiAdminLoginRequestWithBody generates requests for PostApiAdminLogin with any type of body
func NewPostApiAdminLoginRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/admin/login")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetApiHacksRequest generates requests for GetApiHacks
func NewGetApiHacksRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/hacks")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiHacksHackIdRequest generates requests for GetApiHacksHackId
func NewGetApiHacksHackIdRequest(server string, hackId int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "hack_id", runtime.ParamLocationPath, hackId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/hacks/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostApiHacksHackIdEnterRequest calls the generic PostApiHacksHackIdEnter builder with application/json body
func NewPostApiHacksHackIdEnterRequest(server string, hackId int, body PostApiHacksHackIdEnterJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiHacksHackIdEnterRequestWithBody(server, hackId, "application/json", bodyReader)
}

// NewPostApiHacksHackIdEnterRequestWithBody generates requests for PostApiHacksHackIdEnter with any type of body
func NewPostApiHacksHackIdEnterRequestWithBody(server string, hackId int, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "hack_id", runtime.ParamLocationPath, hackId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/hacks/%s/enter", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetApiHacksHackIdInvitationsRequest generates requests for GetApiHacksHackIdInvitations
func NewGetApiHacksHackIdInvitationsRequest(server string, hackId int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "hack_id", runtime.ParamLocationPath, hackId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/hacks/%s/invitations", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiHacksHackIdInvitationsInviteIdAcceptRequest generates requests for GetApiHacksHackIdInvitationsInviteIdAccept
func NewGetApiHacksHackIdInvitationsInviteIdAcceptRequest(server string, hackId int, inviteId int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "hack_id", runtime.ParamLocationPath, hackId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "invite_id", runtime.ParamLocationPath, inviteId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/hacks/%s/invitations/%s/accept", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiHacksHackIdParticipantsRequest generates requests for GetApiHacksHackIdParticipants
func NewGetApiHacksHackIdParticipantsRequest(server string, hackId int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "hack_id", runtime.ParamLocationPath, hackId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/hacks/%s/participants", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiHacksHackIdParticipantsParticipantIdRequest generates requests for GetApiHacksHackIdParticipantsParticipantId
func NewGetApiHacksHackIdParticipantsParticipantIdRequest(server string, hackId int, participantId int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "hack_id", runtime.ParamLocationPath, hackId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "participant_id", runtime.ParamLocationPath, participantId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/hacks/%s/participants/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostApiHacksHackIdParticipantsParticipantsIdInviteRequest generates requests for PostApiHacksHackIdParticipantsParticipantsIdInvite
func NewPostApiHacksHackIdParticipantsParticipantsIdInviteRequest(server string, hackId int, participantsId int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "hack_id", runtime.ParamLocationPath, hackId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "participants_id", runtime.ParamLocationPath, participantsId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/hacks/%s/participants/%s/invite", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiHacksHackIdRequestsRequest generates requests for GetApiHacksHackIdRequests
func NewGetApiHacksHackIdRequestsRequest(server string, hackId int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "hack_id", runtime.ParamLocationPath, hackId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/hacks/%s/requests", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostApiHacksHackIdRequestsRequestIdAcceptRequest generates requests for PostApiHacksHackIdRequestsRequestIdAccept
func NewPostApiHacksHackIdRequestsRequestIdAcceptRequest(server string, hackId int, requestId int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "hack_id", runtime.ParamLocationPath, hackId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "request_id", runtime.ParamLocationPath, requestId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/hacks/%s/requests/%s/accept", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiHacksHackIdTeamsRequest generates requests for GetApiHacksHackIdTeams
func NewGetApiHacksHackIdTeamsRequest(server string, hackId int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "hack_id", runtime.ParamLocationPath, hackId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/hacks/%s/teams", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostApiHacksHackIdTeamsRequest calls the generic PostApiHacksHackIdTeams builder with application/json body
func NewPostApiHacksHackIdTeamsRequest(server string, hackId int, body PostApiHacksHackIdTeamsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiHacksHackIdTeamsRequestWithBody(server, hackId, "application/json", bodyReader)
}

// NewPostApiHacksHackIdTeamsRequestWithBody generates requests for PostApiHacksHackIdTeams with any type of body
func NewPostApiHacksHackIdTeamsRequestWithBody(server string, hackId int, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "hack_id", runtime.ParamLocationPath, hackId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/hacks/%s/teams", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetApiHacksHackIdTeamsTeamIdRequest generates requests for GetApiHacksHackIdTeamsTeamId
func NewGetApiHacksHackIdTeamsTeamIdRequest(server string, hackId int, teamId int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "hack_id", runtime.ParamLocationPath, hackId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "team_id", runtime.ParamLocationPath, teamId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/hacks/%s/teams/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostApiHacksHackIdTeamsTeamIdRequestRequest generates requests for PostApiHacksHackIdTeamsTeamIdRequest
func NewPostApiHacksHackIdTeamsTeamIdRequestRequest(server string, hackId int, teamId int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "hack_id", runtime.ParamLocationPath, hackId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "team_id", runtime.ParamLocationPath, teamId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/hacks/%s/teams/%s/request", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiHealthcheсkRequest generates requests for GetApiHealthcheсk
func NewGetApiHealthcheсkRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/healthcheсk")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostApiLoginRequest calls the generic PostApiLogin builder with application/json body
func NewPostApiLoginRequest(server string, body PostApiLoginJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiLoginRequestWithBody(server, "application/json", bodyReader)
}

// NewPostApiLoginRequestWithBody generates requests for PostApiLogin with any type of body
func NewPostApiLoginRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/login")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetApiRolesRequest generates requests for GetApiRoles
func NewGetApiRolesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/roles")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiSkillsRequest generates requests for GetApiSkills
func NewGetApiSkillsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/skills")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiUserRequest generates requests for GetApiUser
func NewGetApiUserRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/user")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiUsersUserIdRequest generates requests for GetApiUsersUserId
func NewGetApiUsersUserIdRequest(server string, userId int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "user_id", runtime.ParamLocationPath, userId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/users/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiUsersUserIdTeamsRequest generates requests for GetApiUsersUserIdTeams
func NewGetApiUsersUserIdTeamsRequest(server string, userId int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "user_id", runtime.ParamLocationPath, userId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/users/%s/teams", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostApiAdminHacksWithBodyWithResponse request with any body
	PostApiAdminHacksWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiAdminHacksResponse, error)

	PostApiAdminHacksWithResponse(ctx context.Context, body PostApiAdminHacksJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiAdminHacksResponse, error)

	// PostApiAdminLoginWithBodyWithResponse request with any body
	PostApiAdminLoginWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiAdminLoginResponse, error)

	PostApiAdminLoginWithResponse(ctx context.Context, body PostApiAdminLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiAdminLoginResponse, error)

	// GetApiHacksWithResponse request
	GetApiHacksWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiHacksResponse, error)

	// GetApiHacksHackIdWithResponse request
	GetApiHacksHackIdWithResponse(ctx context.Context, hackId int, reqEditors ...RequestEditorFn) (*GetApiHacksHackIdResponse, error)

	// PostApiHacksHackIdEnterWithBodyWithResponse request with any body
	PostApiHacksHackIdEnterWithBodyWithResponse(ctx context.Context, hackId int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiHacksHackIdEnterResponse, error)

	PostApiHacksHackIdEnterWithResponse(ctx context.Context, hackId int, body PostApiHacksHackIdEnterJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiHacksHackIdEnterResponse, error)

	// GetApiHacksHackIdInvitationsWithResponse request
	GetApiHacksHackIdInvitationsWithResponse(ctx context.Context, hackId int, reqEditors ...RequestEditorFn) (*GetApiHacksHackIdInvitationsResponse, error)

	// GetApiHacksHackIdInvitationsInviteIdAcceptWithResponse request
	GetApiHacksHackIdInvitationsInviteIdAcceptWithResponse(ctx context.Context, hackId int, inviteId int, reqEditors ...RequestEditorFn) (*GetApiHacksHackIdInvitationsInviteIdAcceptResponse, error)

	// GetApiHacksHackIdParticipantsWithResponse request
	GetApiHacksHackIdParticipantsWithResponse(ctx context.Context, hackId int, reqEditors ...RequestEditorFn) (*GetApiHacksHackIdParticipantsResponse, error)

	// GetApiHacksHackIdParticipantsParticipantIdWithResponse request
	GetApiHacksHackIdParticipantsParticipantIdWithResponse(ctx context.Context, hackId int, participantId int, reqEditors ...RequestEditorFn) (*GetApiHacksHackIdParticipantsParticipantIdResponse, error)

	// PostApiHacksHackIdParticipantsParticipantsIdInviteWithResponse request
	PostApiHacksHackIdParticipantsParticipantsIdInviteWithResponse(ctx context.Context, hackId int, participantsId int, reqEditors ...RequestEditorFn) (*PostApiHacksHackIdParticipantsParticipantsIdInviteResponse, error)

	// GetApiHacksHackIdRequestsWithResponse request
	GetApiHacksHackIdRequestsWithResponse(ctx context.Context, hackId int, reqEditors ...RequestEditorFn) (*GetApiHacksHackIdRequestsResponse, error)

	// PostApiHacksHackIdRequestsRequestIdAcceptWithResponse request
	PostApiHacksHackIdRequestsRequestIdAcceptWithResponse(ctx context.Context, hackId int, requestId int, reqEditors ...RequestEditorFn) (*PostApiHacksHackIdRequestsRequestIdAcceptResponse, error)

	// GetApiHacksHackIdTeamsWithResponse request
	GetApiHacksHackIdTeamsWithResponse(ctx context.Context, hackId int, reqEditors ...RequestEditorFn) (*GetApiHacksHackIdTeamsResponse, error)

	// PostApiHacksHackIdTeamsWithBodyWithResponse request with any body
	PostApiHacksHackIdTeamsWithBodyWithResponse(ctx context.Context, hackId int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiHacksHackIdTeamsResponse, error)

	PostApiHacksHackIdTeamsWithResponse(ctx context.Context, hackId int, body PostApiHacksHackIdTeamsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiHacksHackIdTeamsResponse, error)

	// GetApiHacksHackIdTeamsTeamIdWithResponse request
	GetApiHacksHackIdTeamsTeamIdWithResponse(ctx context.Context, hackId int, teamId int, reqEditors ...RequestEditorFn) (*GetApiHacksHackIdTeamsTeamIdResponse, error)

	// PostApiHacksHackIdTeamsTeamIdRequestWithResponse request
	PostApiHacksHackIdTeamsTeamIdRequestWithResponse(ctx context.Context, hackId int, teamId int, reqEditors ...RequestEditorFn) (*PostApiHacksHackIdTeamsTeamIdRequestResponse, error)

	// GetApiHealthcheсkWithResponse request
	GetApiHealthcheсkWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiHealthcheсkResponse, error)

	// PostApiLoginWithBodyWithResponse request with any body
	PostApiLoginWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiLoginResponse, error)

	PostApiLoginWithResponse(ctx context.Context, body PostApiLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiLoginResponse, error)

	// GetApiRolesWithResponse request
	GetApiRolesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiRolesResponse, error)

	// GetApiSkillsWithResponse request
	GetApiSkillsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiSkillsResponse, error)

	// GetApiUserWithResponse request
	GetApiUserWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiUserResponse, error)

	// GetApiUsersUserIdWithResponse request
	GetApiUsersUserIdWithResponse(ctx context.Context, userId int, reqEditors ...RequestEditorFn) (*GetApiUsersUserIdResponse, error)

	// GetApiUsersUserIdTeamsWithResponse request
	GetApiUsersUserIdTeamsWithResponse(ctx context.Context, userId int, reqEditors ...RequestEditorFn) (*GetApiUsersUserIdTeamsResponse, error)
}

type PostApiAdminHacksResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HackathonShort
}

// Status returns HTTPResponse.Status
func (r PostApiAdminHacksResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiAdminHacksResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostApiAdminLoginResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Token
}

// Status returns HTTPResponse.Status
func (r PostApiAdminLoginResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiAdminLoginResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiHacksResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]HackathonShort
}

// Status returns HTTPResponse.Status
func (r GetApiHacksResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiHacksResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiHacksHackIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HackathonPage
}

// Status returns HTTPResponse.Status
func (r GetApiHacksHackIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiHacksHackIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostApiHacksHackIdEnterResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostApiHacksHackIdEnterResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiHacksHackIdEnterResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiHacksHackIdInvitationsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Invite
}

// Status returns HTTPResponse.Status
func (r GetApiHacksHackIdInvitationsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiHacksHackIdInvitationsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiHacksHackIdInvitationsInviteIdAcceptResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetApiHacksHackIdInvitationsInviteIdAcceptResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiHacksHackIdInvitationsInviteIdAcceptResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiHacksHackIdParticipantsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Participant
}

// Status returns HTTPResponse.Status
func (r GetApiHacksHackIdParticipantsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiHacksHackIdParticipantsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiHacksHackIdParticipantsParticipantIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Participant
}

// Status returns HTTPResponse.Status
func (r GetApiHacksHackIdParticipantsParticipantIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiHacksHackIdParticipantsParticipantIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostApiHacksHackIdParticipantsParticipantsIdInviteResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostApiHacksHackIdParticipantsParticipantsIdInviteResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiHacksHackIdParticipantsParticipantsIdInviteResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiHacksHackIdRequestsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Request
}

// Status returns HTTPResponse.Status
func (r GetApiHacksHackIdRequestsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiHacksHackIdRequestsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostApiHacksHackIdRequestsRequestIdAcceptResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostApiHacksHackIdRequestsRequestIdAcceptResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiHacksHackIdRequestsRequestIdAcceptResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiHacksHackIdTeamsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Team
}

// Status returns HTTPResponse.Status
func (r GetApiHacksHackIdTeamsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiHacksHackIdTeamsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostApiHacksHackIdTeamsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *[]Team
}

// Status returns HTTPResponse.Status
func (r PostApiHacksHackIdTeamsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiHacksHackIdTeamsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiHacksHackIdTeamsTeamIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Team
}

// Status returns HTTPResponse.Status
func (r GetApiHacksHackIdTeamsTeamIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiHacksHackIdTeamsTeamIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostApiHacksHackIdTeamsTeamIdRequestResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostApiHacksHackIdTeamsTeamIdRequestResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiHacksHackIdTeamsTeamIdRequestResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiHealthcheсkResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Health
}

// Status returns HTTPResponse.Status
func (r GetApiHealthcheсkResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiHealthcheсkResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostApiLoginResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Token
}

// Status returns HTTPResponse.Status
func (r PostApiLoginResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiLoginResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiRolesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Role
}

// Status returns HTTPResponse.Status
func (r GetApiRolesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiRolesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiSkillsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Skill
}

// Status returns HTTPResponse.Status
func (r GetApiSkillsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiSkillsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiUserResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *User
}

// Status returns HTTPResponse.Status
func (r GetApiUserResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiUserResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiUsersUserIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *User
}

// Status returns HTTPResponse.Status
func (r GetApiUsersUserIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiUsersUserIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiUsersUserIdTeamsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]TeamShort
}

// Status returns HTTPResponse.Status
func (r GetApiUsersUserIdTeamsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiUsersUserIdTeamsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostApiAdminHacksWithBodyWithResponse request with arbitrary body returning *PostApiAdminHacksResponse
func (c *ClientWithResponses) PostApiAdminHacksWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiAdminHacksResponse, error) {
	rsp, err := c.PostApiAdminHacksWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiAdminHacksResponse(rsp)
}

func (c *ClientWithResponses) PostApiAdminHacksWithResponse(ctx context.Context, body PostApiAdminHacksJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiAdminHacksResponse, error) {
	rsp, err := c.PostApiAdminHacks(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiAdminHacksResponse(rsp)
}

// PostApiAdminLoginWithBodyWithResponse request with arbitrary body returning *PostApiAdminLoginResponse
func (c *ClientWithResponses) PostApiAdminLoginWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiAdminLoginResponse, error) {
	rsp, err := c.PostApiAdminLoginWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiAdminLoginResponse(rsp)
}

func (c *ClientWithResponses) PostApiAdminLoginWithResponse(ctx context.Context, body PostApiAdminLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiAdminLoginResponse, error) {
	rsp, err := c.PostApiAdminLogin(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiAdminLoginResponse(rsp)
}

// GetApiHacksWithResponse request returning *GetApiHacksResponse
func (c *ClientWithResponses) GetApiHacksWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiHacksResponse, error) {
	rsp, err := c.GetApiHacks(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiHacksResponse(rsp)
}

// GetApiHacksHackIdWithResponse request returning *GetApiHacksHackIdResponse
func (c *ClientWithResponses) GetApiHacksHackIdWithResponse(ctx context.Context, hackId int, reqEditors ...RequestEditorFn) (*GetApiHacksHackIdResponse, error) {
	rsp, err := c.GetApiHacksHackId(ctx, hackId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiHacksHackIdResponse(rsp)
}

// PostApiHacksHackIdEnterWithBodyWithResponse request with arbitrary body returning *PostApiHacksHackIdEnterResponse
func (c *ClientWithResponses) PostApiHacksHackIdEnterWithBodyWithResponse(ctx context.Context, hackId int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiHacksHackIdEnterResponse, error) {
	rsp, err := c.PostApiHacksHackIdEnterWithBody(ctx, hackId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiHacksHackIdEnterResponse(rsp)
}

func (c *ClientWithResponses) PostApiHacksHackIdEnterWithResponse(ctx context.Context, hackId int, body PostApiHacksHackIdEnterJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiHacksHackIdEnterResponse, error) {
	rsp, err := c.PostApiHacksHackIdEnter(ctx, hackId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiHacksHackIdEnterResponse(rsp)
}

// GetApiHacksHackIdInvitationsWithResponse request returning *GetApiHacksHackIdInvitationsResponse
func (c *ClientWithResponses) GetApiHacksHackIdInvitationsWithResponse(ctx context.Context, hackId int, reqEditors ...RequestEditorFn) (*GetApiHacksHackIdInvitationsResponse, error) {
	rsp, err := c.GetApiHacksHackIdInvitations(ctx, hackId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiHacksHackIdInvitationsResponse(rsp)
}

// GetApiHacksHackIdInvitationsInviteIdAcceptWithResponse request returning *GetApiHacksHackIdInvitationsInviteIdAcceptResponse
func (c *ClientWithResponses) GetApiHacksHackIdInvitationsInviteIdAcceptWithResponse(ctx context.Context, hackId int, inviteId int, reqEditors ...RequestEditorFn) (*GetApiHacksHackIdInvitationsInviteIdAcceptResponse, error) {
	rsp, err := c.GetApiHacksHackIdInvitationsInviteIdAccept(ctx, hackId, inviteId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiHacksHackIdInvitationsInviteIdAcceptResponse(rsp)
}

// GetApiHacksHackIdParticipantsWithResponse request returning *GetApiHacksHackIdParticipantsResponse
func (c *ClientWithResponses) GetApiHacksHackIdParticipantsWithResponse(ctx context.Context, hackId int, reqEditors ...RequestEditorFn) (*GetApiHacksHackIdParticipantsResponse, error) {
	rsp, err := c.GetApiHacksHackIdParticipants(ctx, hackId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiHacksHackIdParticipantsResponse(rsp)
}

// GetApiHacksHackIdParticipantsParticipantIdWithResponse request returning *GetApiHacksHackIdParticipantsParticipantIdResponse
func (c *ClientWithResponses) GetApiHacksHackIdParticipantsParticipantIdWithResponse(ctx context.Context, hackId int, participantId int, reqEditors ...RequestEditorFn) (*GetApiHacksHackIdParticipantsParticipantIdResponse, error) {
	rsp, err := c.GetApiHacksHackIdParticipantsParticipantId(ctx, hackId, participantId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiHacksHackIdParticipantsParticipantIdResponse(rsp)
}

// PostApiHacksHackIdParticipantsParticipantsIdInviteWithResponse request returning *PostApiHacksHackIdParticipantsParticipantsIdInviteResponse
func (c *ClientWithResponses) PostApiHacksHackIdParticipantsParticipantsIdInviteWithResponse(ctx context.Context, hackId int, participantsId int, reqEditors ...RequestEditorFn) (*PostApiHacksHackIdParticipantsParticipantsIdInviteResponse, error) {
	rsp, err := c.PostApiHacksHackIdParticipantsParticipantsIdInvite(ctx, hackId, participantsId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiHacksHackIdParticipantsParticipantsIdInviteResponse(rsp)
}

// GetApiHacksHackIdRequestsWithResponse request returning *GetApiHacksHackIdRequestsResponse
func (c *ClientWithResponses) GetApiHacksHackIdRequestsWithResponse(ctx context.Context, hackId int, reqEditors ...RequestEditorFn) (*GetApiHacksHackIdRequestsResponse, error) {
	rsp, err := c.GetApiHacksHackIdRequests(ctx, hackId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiHacksHackIdRequestsResponse(rsp)
}

// PostApiHacksHackIdRequestsRequestIdAcceptWithResponse request returning *PostApiHacksHackIdRequestsRequestIdAcceptResponse
func (c *ClientWithResponses) PostApiHacksHackIdRequestsRequestIdAcceptWithResponse(ctx context.Context, hackId int, requestId int, reqEditors ...RequestEditorFn) (*PostApiHacksHackIdRequestsRequestIdAcceptResponse, error) {
	rsp, err := c.PostApiHacksHackIdRequestsRequestIdAccept(ctx, hackId, requestId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiHacksHackIdRequestsRequestIdAcceptResponse(rsp)
}

// GetApiHacksHackIdTeamsWithResponse request returning *GetApiHacksHackIdTeamsResponse
func (c *ClientWithResponses) GetApiHacksHackIdTeamsWithResponse(ctx context.Context, hackId int, reqEditors ...RequestEditorFn) (*GetApiHacksHackIdTeamsResponse, error) {
	rsp, err := c.GetApiHacksHackIdTeams(ctx, hackId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiHacksHackIdTeamsResponse(rsp)
}

// PostApiHacksHackIdTeamsWithBodyWithResponse request with arbitrary body returning *PostApiHacksHackIdTeamsResponse
func (c *ClientWithResponses) PostApiHacksHackIdTeamsWithBodyWithResponse(ctx context.Context, hackId int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiHacksHackIdTeamsResponse, error) {
	rsp, err := c.PostApiHacksHackIdTeamsWithBody(ctx, hackId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiHacksHackIdTeamsResponse(rsp)
}

func (c *ClientWithResponses) PostApiHacksHackIdTeamsWithResponse(ctx context.Context, hackId int, body PostApiHacksHackIdTeamsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiHacksHackIdTeamsResponse, error) {
	rsp, err := c.PostApiHacksHackIdTeams(ctx, hackId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiHacksHackIdTeamsResponse(rsp)
}

// GetApiHacksHackIdTeamsTeamIdWithResponse request returning *GetApiHacksHackIdTeamsTeamIdResponse
func (c *ClientWithResponses) GetApiHacksHackIdTeamsTeamIdWithResponse(ctx context.Context, hackId int, teamId int, reqEditors ...RequestEditorFn) (*GetApiHacksHackIdTeamsTeamIdResponse, error) {
	rsp, err := c.GetApiHacksHackIdTeamsTeamId(ctx, hackId, teamId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiHacksHackIdTeamsTeamIdResponse(rsp)
}

// PostApiHacksHackIdTeamsTeamIdRequestWithResponse request returning *PostApiHacksHackIdTeamsTeamIdRequestResponse
func (c *ClientWithResponses) PostApiHacksHackIdTeamsTeamIdRequestWithResponse(ctx context.Context, hackId int, teamId int, reqEditors ...RequestEditorFn) (*PostApiHacksHackIdTeamsTeamIdRequestResponse, error) {
	rsp, err := c.PostApiHacksHackIdTeamsTeamIdRequest(ctx, hackId, teamId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiHacksHackIdTeamsTeamIdRequestResponse(rsp)
}

// GetApiHealthcheсkWithResponse request returning *GetApiHealthcheсkResponse
func (c *ClientWithResponses) GetApiHealthcheсkWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiHealthcheсkResponse, error) {
	rsp, err := c.GetApiHealthcheсk(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiHealthcheсkResponse(rsp)
}

// PostApiLoginWithBodyWithResponse request with arbitrary body returning *PostApiLoginResponse
func (c *ClientWithResponses) PostApiLoginWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiLoginResponse, error) {
	rsp, err := c.PostApiLoginWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiLoginResponse(rsp)
}

func (c *ClientWithResponses) PostApiLoginWithResponse(ctx context.Context, body PostApiLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiLoginResponse, error) {
	rsp, err := c.PostApiLogin(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiLoginResponse(rsp)
}

// GetApiRolesWithResponse request returning *GetApiRolesResponse
func (c *ClientWithResponses) GetApiRolesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiRolesResponse, error) {
	rsp, err := c.GetApiRoles(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiRolesResponse(rsp)
}

// GetApiSkillsWithResponse request returning *GetApiSkillsResponse
func (c *ClientWithResponses) GetApiSkillsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiSkillsResponse, error) {
	rsp, err := c.GetApiSkills(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiSkillsResponse(rsp)
}

// GetApiUserWithResponse request returning *GetApiUserResponse
func (c *ClientWithResponses) GetApiUserWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiUserResponse, error) {
	rsp, err := c.GetApiUser(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiUserResponse(rsp)
}

// GetApiUsersUserIdWithResponse request returning *GetApiUsersUserIdResponse
func (c *ClientWithResponses) GetApiUsersUserIdWithResponse(ctx context.Context, userId int, reqEditors ...RequestEditorFn) (*GetApiUsersUserIdResponse, error) {
	rsp, err := c.GetApiUsersUserId(ctx, userId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiUsersUserIdResponse(rsp)
}

// GetApiUsersUserIdTeamsWithResponse request returning *GetApiUsersUserIdTeamsResponse
func (c *ClientWithResponses) GetApiUsersUserIdTeamsWithResponse(ctx context.Context, userId int, reqEditors ...RequestEditorFn) (*GetApiUsersUserIdTeamsResponse, error) {
	rsp, err := c.GetApiUsersUserIdTeams(ctx, userId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiUsersUserIdTeamsResponse(rsp)
}

// ParsePostApiAdminHacksResponse parses an HTTP response from a PostApiAdminHacksWithResponse call
func ParsePostApiAdminHacksResponse(rsp *http.Response) (*PostApiAdminHacksResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiAdminHacksResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HackathonShort
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostApiAdminLoginResponse parses an HTTP response from a PostApiAdminLoginWithResponse call
func ParsePostApiAdminLoginResponse(rsp *http.Response) (*PostApiAdminLoginResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiAdminLoginResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Token
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetApiHacksResponse parses an HTTP response from a GetApiHacksWithResponse call
func ParseGetApiHacksResponse(rsp *http.Response) (*GetApiHacksResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiHacksResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []HackathonShort
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetApiHacksHackIdResponse parses an HTTP response from a GetApiHacksHackIdWithResponse call
func ParseGetApiHacksHackIdResponse(rsp *http.Response) (*GetApiHacksHackIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiHacksHackIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HackathonPage
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostApiHacksHackIdEnterResponse parses an HTTP response from a PostApiHacksHackIdEnterWithResponse call
func ParsePostApiHacksHackIdEnterResponse(rsp *http.Response) (*PostApiHacksHackIdEnterResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiHacksHackIdEnterResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetApiHacksHackIdInvitationsResponse parses an HTTP response from a GetApiHacksHackIdInvitationsWithResponse call
func ParseGetApiHacksHackIdInvitationsResponse(rsp *http.Response) (*GetApiHacksHackIdInvitationsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiHacksHackIdInvitationsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Invite
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetApiHacksHackIdInvitationsInviteIdAcceptResponse parses an HTTP response from a GetApiHacksHackIdInvitationsInviteIdAcceptWithResponse call
func ParseGetApiHacksHackIdInvitationsInviteIdAcceptResponse(rsp *http.Response) (*GetApiHacksHackIdInvitationsInviteIdAcceptResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiHacksHackIdInvitationsInviteIdAcceptResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetApiHacksHackIdParticipantsResponse parses an HTTP response from a GetApiHacksHackIdParticipantsWithResponse call
func ParseGetApiHacksHackIdParticipantsResponse(rsp *http.Response) (*GetApiHacksHackIdParticipantsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiHacksHackIdParticipantsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Participant
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetApiHacksHackIdParticipantsParticipantIdResponse parses an HTTP response from a GetApiHacksHackIdParticipantsParticipantIdWithResponse call
func ParseGetApiHacksHackIdParticipantsParticipantIdResponse(rsp *http.Response) (*GetApiHacksHackIdParticipantsParticipantIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiHacksHackIdParticipantsParticipantIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Participant
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostApiHacksHackIdParticipantsParticipantsIdInviteResponse parses an HTTP response from a PostApiHacksHackIdParticipantsParticipantsIdInviteWithResponse call
func ParsePostApiHacksHackIdParticipantsParticipantsIdInviteResponse(rsp *http.Response) (*PostApiHacksHackIdParticipantsParticipantsIdInviteResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiHacksHackIdParticipantsParticipantsIdInviteResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetApiHacksHackIdRequestsResponse parses an HTTP response from a GetApiHacksHackIdRequestsWithResponse call
func ParseGetApiHacksHackIdRequestsResponse(rsp *http.Response) (*GetApiHacksHackIdRequestsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiHacksHackIdRequestsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Request
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostApiHacksHackIdRequestsRequestIdAcceptResponse parses an HTTP response from a PostApiHacksHackIdRequestsRequestIdAcceptWithResponse call
func ParsePostApiHacksHackIdRequestsRequestIdAcceptResponse(rsp *http.Response) (*PostApiHacksHackIdRequestsRequestIdAcceptResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiHacksHackIdRequestsRequestIdAcceptResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetApiHacksHackIdTeamsResponse parses an HTTP response from a GetApiHacksHackIdTeamsWithResponse call
func ParseGetApiHacksHackIdTeamsResponse(rsp *http.Response) (*GetApiHacksHackIdTeamsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiHacksHackIdTeamsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Team
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostApiHacksHackIdTeamsResponse parses an HTTP response from a PostApiHacksHackIdTeamsWithResponse call
func ParsePostApiHacksHackIdTeamsResponse(rsp *http.Response) (*PostApiHacksHackIdTeamsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiHacksHackIdTeamsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest []Team
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}

// ParseGetApiHacksHackIdTeamsTeamIdResponse parses an HTTP response from a GetApiHacksHackIdTeamsTeamIdWithResponse call
func ParseGetApiHacksHackIdTeamsTeamIdResponse(rsp *http.Response) (*GetApiHacksHackIdTeamsTeamIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiHacksHackIdTeamsTeamIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Team
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostApiHacksHackIdTeamsTeamIdRequestResponse parses an HTTP response from a PostApiHacksHackIdTeamsTeamIdRequestWithResponse call
func ParsePostApiHacksHackIdTeamsTeamIdRequestResponse(rsp *http.Response) (*PostApiHacksHackIdTeamsTeamIdRequestResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiHacksHackIdTeamsTeamIdRequestResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetApiHealthcheсkResponse parses an HTTP response from a GetApiHealthcheсkWithResponse call
func ParseGetApiHealthcheсkResponse(rsp *http.Response) (*GetApiHealthcheсkResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiHealthcheсkResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Health
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostApiLoginResponse parses an HTTP response from a PostApiLoginWithResponse call
func ParsePostApiLoginResponse(rsp *http.Response) (*PostApiLoginResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiLoginResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Token
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetApiRolesResponse parses an HTTP response from a GetApiRolesWithResponse call
func ParseGetApiRolesResponse(rsp *http.Response) (*GetApiRolesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiRolesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Role
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetApiSkillsResponse parses an HTTP response from a GetApiSkillsWithResponse call
func ParseGetApiSkillsResponse(rsp *http.Response) (*GetApiSkillsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiSkillsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Skill
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetApiUserResponse parses an HTTP response from a GetApiUserWithResponse call
func ParseGetApiUserResponse(rsp *http.Response) (*GetApiUserResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiUserResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest User
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetApiUsersUserIdResponse parses an HTTP response from a GetApiUsersUserIdWithResponse call
func ParseGetApiUsersUserIdResponse(rsp *http.Response) (*GetApiUsersUserIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiUsersUserIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest User
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetApiUsersUserIdTeamsResponse parses an HTTP response from a GetApiUsersUserIdTeamsWithResponse call
func ParseGetApiUsersUserIdTeamsResponse(rsp *http.Response) (*GetApiUsersUserIdTeamsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiUsersUserIdTeamsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []TeamShort
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
