// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostAdminHacksWithBody request with any body
	PostAdminHacksWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostAdminHacks(ctx context.Context, body PostAdminHacksJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostAdminLoginWithBody request with any body
	PostAdminLoginWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostAdminLogin(ctx context.Context, body PostAdminLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHacks request
	GetHacks(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHacksHackId request
	GetHacksHackId(ctx context.Context, hackId int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostHacksHackIdEnterWithBody request with any body
	PostHacksHackIdEnterWithBody(ctx context.Context, hackId int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostHacksHackIdEnter(ctx context.Context, hackId int, body PostHacksHackIdEnterJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHacksHackIdInvitations request
	GetHacksHackIdInvitations(ctx context.Context, hackId int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHacksHackIdInvitationsInviteIdAccept request
	GetHacksHackIdInvitationsInviteIdAccept(ctx context.Context, hackId int, inviteId int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHacksHackIdParticipants request
	GetHacksHackIdParticipants(ctx context.Context, hackId int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHacksHackIdParticipantsParticipantId request
	GetHacksHackIdParticipantsParticipantId(ctx context.Context, hackId int, participantId int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostHacksHackIdParticipantsParticipantsIdInvite request
	PostHacksHackIdParticipantsParticipantsIdInvite(ctx context.Context, hackId int, participantsId int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHacksHackIdRequests request
	GetHacksHackIdRequests(ctx context.Context, hackId int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostHacksHackIdRequestsRequestIdAccept request
	PostHacksHackIdRequestsRequestIdAccept(ctx context.Context, hackId int, requestId int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHacksHackIdTeams request
	GetHacksHackIdTeams(ctx context.Context, hackId int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostHacksHackIdTeamsWithBody request with any body
	PostHacksHackIdTeamsWithBody(ctx context.Context, hackId int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostHacksHackIdTeams(ctx context.Context, hackId int, body PostHacksHackIdTeamsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHacksHackIdTeamsTeamId request
	GetHacksHackIdTeamsTeamId(ctx context.Context, hackId int, teamId int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostHacksHackIdTeamsTeamIdRequest request
	PostHacksHackIdTeamsTeamIdRequest(ctx context.Context, hackId int, teamId int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostLoginWithBody request with any body
	PostLoginWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostLogin(ctx context.Context, body PostLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetUsersUserId request
	GetUsersUserId(ctx context.Context, userId int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetUsersUserIdTeams request
	GetUsersUserIdTeams(ctx context.Context, userId int, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostAdminHacksWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAdminHacksRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAdminHacks(ctx context.Context, body PostAdminHacksJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAdminHacksRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAdminLoginWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAdminLoginRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAdminLogin(ctx context.Context, body PostAdminLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAdminLoginRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHacks(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHacksRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHacksHackId(ctx context.Context, hackId int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHacksHackIdRequest(c.Server, hackId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostHacksHackIdEnterWithBody(ctx context.Context, hackId int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostHacksHackIdEnterRequestWithBody(c.Server, hackId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostHacksHackIdEnter(ctx context.Context, hackId int, body PostHacksHackIdEnterJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostHacksHackIdEnterRequest(c.Server, hackId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHacksHackIdInvitations(ctx context.Context, hackId int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHacksHackIdInvitationsRequest(c.Server, hackId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHacksHackIdInvitationsInviteIdAccept(ctx context.Context, hackId int, inviteId int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHacksHackIdInvitationsInviteIdAcceptRequest(c.Server, hackId, inviteId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHacksHackIdParticipants(ctx context.Context, hackId int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHacksHackIdParticipantsRequest(c.Server, hackId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHacksHackIdParticipantsParticipantId(ctx context.Context, hackId int, participantId int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHacksHackIdParticipantsParticipantIdRequest(c.Server, hackId, participantId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostHacksHackIdParticipantsParticipantsIdInvite(ctx context.Context, hackId int, participantsId int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostHacksHackIdParticipantsParticipantsIdInviteRequest(c.Server, hackId, participantsId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHacksHackIdRequests(ctx context.Context, hackId int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHacksHackIdRequestsRequest(c.Server, hackId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostHacksHackIdRequestsRequestIdAccept(ctx context.Context, hackId int, requestId int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostHacksHackIdRequestsRequestIdAcceptRequest(c.Server, hackId, requestId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHacksHackIdTeams(ctx context.Context, hackId int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHacksHackIdTeamsRequest(c.Server, hackId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostHacksHackIdTeamsWithBody(ctx context.Context, hackId int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostHacksHackIdTeamsRequestWithBody(c.Server, hackId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostHacksHackIdTeams(ctx context.Context, hackId int, body PostHacksHackIdTeamsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostHacksHackIdTeamsRequest(c.Server, hackId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHacksHackIdTeamsTeamId(ctx context.Context, hackId int, teamId int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHacksHackIdTeamsTeamIdRequest(c.Server, hackId, teamId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostHacksHackIdTeamsTeamIdRequest(ctx context.Context, hackId int, teamId int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostHacksHackIdTeamsTeamIdRequestRequest(c.Server, hackId, teamId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostLoginWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostLoginRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostLogin(ctx context.Context, body PostLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostLoginRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetUsersUserId(ctx context.Context, userId int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetUsersUserIdRequest(c.Server, userId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetUsersUserIdTeams(ctx context.Context, userId int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetUsersUserIdTeamsRequest(c.Server, userId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostAdminHacksRequest calls the generic PostAdminHacks builder with application/json body
func NewPostAdminHacksRequest(server string, body PostAdminHacksJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostAdminHacksRequestWithBody(server, "application/json", bodyReader)
}

// NewPostAdminHacksRequestWithBody generates requests for PostAdminHacks with any type of body
func NewPostAdminHacksRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/hacks")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostAdminLoginRequest calls the generic PostAdminLogin builder with application/json body
func NewPostAdminLoginRequest(server string, body PostAdminLoginJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostAdminLoginRequestWithBody(server, "application/json", bodyReader)
}

// NewPostAdminLoginRequestWithBody generates requests for PostAdminLogin with any type of body
func NewPostAdminLoginRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/admin/login")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetHacksRequest generates requests for GetHacks
func NewGetHacksRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hacks")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHacksHackIdRequest generates requests for GetHacksHackId
func NewGetHacksHackIdRequest(server string, hackId int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "hack_id", runtime.ParamLocationPath, hackId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hacks/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostHacksHackIdEnterRequest calls the generic PostHacksHackIdEnter builder with application/json body
func NewPostHacksHackIdEnterRequest(server string, hackId int, body PostHacksHackIdEnterJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostHacksHackIdEnterRequestWithBody(server, hackId, "application/json", bodyReader)
}

// NewPostHacksHackIdEnterRequestWithBody generates requests for PostHacksHackIdEnter with any type of body
func NewPostHacksHackIdEnterRequestWithBody(server string, hackId int, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "hack_id", runtime.ParamLocationPath, hackId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hacks/%s/enter", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetHacksHackIdInvitationsRequest generates requests for GetHacksHackIdInvitations
func NewGetHacksHackIdInvitationsRequest(server string, hackId int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "hack_id", runtime.ParamLocationPath, hackId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hacks/%s/invitations", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHacksHackIdInvitationsInviteIdAcceptRequest generates requests for GetHacksHackIdInvitationsInviteIdAccept
func NewGetHacksHackIdInvitationsInviteIdAcceptRequest(server string, hackId int, inviteId int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "hack_id", runtime.ParamLocationPath, hackId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "invite_id", runtime.ParamLocationPath, inviteId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hacks/%s/invitations/%s/accept", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHacksHackIdParticipantsRequest generates requests for GetHacksHackIdParticipants
func NewGetHacksHackIdParticipantsRequest(server string, hackId int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "hack_id", runtime.ParamLocationPath, hackId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hacks/%s/participants", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHacksHackIdParticipantsParticipantIdRequest generates requests for GetHacksHackIdParticipantsParticipantId
func NewGetHacksHackIdParticipantsParticipantIdRequest(server string, hackId int, participantId int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "hack_id", runtime.ParamLocationPath, hackId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "participant_id", runtime.ParamLocationPath, participantId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hacks/%s/participants/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostHacksHackIdParticipantsParticipantsIdInviteRequest generates requests for PostHacksHackIdParticipantsParticipantsIdInvite
func NewPostHacksHackIdParticipantsParticipantsIdInviteRequest(server string, hackId int, participantsId int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "hack_id", runtime.ParamLocationPath, hackId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "participants_id", runtime.ParamLocationPath, participantsId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hacks/%s/participants/%s/invite", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHacksHackIdRequestsRequest generates requests for GetHacksHackIdRequests
func NewGetHacksHackIdRequestsRequest(server string, hackId int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "hack_id", runtime.ParamLocationPath, hackId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hacks/%s/requests", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostHacksHackIdRequestsRequestIdAcceptRequest generates requests for PostHacksHackIdRequestsRequestIdAccept
func NewPostHacksHackIdRequestsRequestIdAcceptRequest(server string, hackId int, requestId int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "hack_id", runtime.ParamLocationPath, hackId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "request_id", runtime.ParamLocationPath, requestId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hacks/%s/requests/%s/accept", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHacksHackIdTeamsRequest generates requests for GetHacksHackIdTeams
func NewGetHacksHackIdTeamsRequest(server string, hackId int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "hack_id", runtime.ParamLocationPath, hackId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hacks/%s/teams", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostHacksHackIdTeamsRequest calls the generic PostHacksHackIdTeams builder with application/json body
func NewPostHacksHackIdTeamsRequest(server string, hackId int, body PostHacksHackIdTeamsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostHacksHackIdTeamsRequestWithBody(server, hackId, "application/json", bodyReader)
}

// NewPostHacksHackIdTeamsRequestWithBody generates requests for PostHacksHackIdTeams with any type of body
func NewPostHacksHackIdTeamsRequestWithBody(server string, hackId int, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "hack_id", runtime.ParamLocationPath, hackId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hacks/%s/teams", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetHacksHackIdTeamsTeamIdRequest generates requests for GetHacksHackIdTeamsTeamId
func NewGetHacksHackIdTeamsTeamIdRequest(server string, hackId int, teamId int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "hack_id", runtime.ParamLocationPath, hackId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "team_id", runtime.ParamLocationPath, teamId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hacks/%s/teams/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostHacksHackIdTeamsTeamIdRequestRequest generates requests for PostHacksHackIdTeamsTeamIdRequest
func NewPostHacksHackIdTeamsTeamIdRequestRequest(server string, hackId int, teamId int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "hack_id", runtime.ParamLocationPath, hackId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "team_id", runtime.ParamLocationPath, teamId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hacks/%s/teams/%s/request", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostLoginRequest calls the generic PostLogin builder with application/json body
func NewPostLoginRequest(server string, body PostLoginJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostLoginRequestWithBody(server, "application/json", bodyReader)
}

// NewPostLoginRequestWithBody generates requests for PostLogin with any type of body
func NewPostLoginRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/login")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetUsersUserIdRequest generates requests for GetUsersUserId
func NewGetUsersUserIdRequest(server string, userId int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "user_id", runtime.ParamLocationPath, userId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/users/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetUsersUserIdTeamsRequest generates requests for GetUsersUserIdTeams
func NewGetUsersUserIdTeamsRequest(server string, userId int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "user_id", runtime.ParamLocationPath, userId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/users/%s/teams", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostAdminHacksWithBodyWithResponse request with any body
	PostAdminHacksWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAdminHacksResponse, error)

	PostAdminHacksWithResponse(ctx context.Context, body PostAdminHacksJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAdminHacksResponse, error)

	// PostAdminLoginWithBodyWithResponse request with any body
	PostAdminLoginWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAdminLoginResponse, error)

	PostAdminLoginWithResponse(ctx context.Context, body PostAdminLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAdminLoginResponse, error)

	// GetHacksWithResponse request
	GetHacksWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHacksResponse, error)

	// GetHacksHackIdWithResponse request
	GetHacksHackIdWithResponse(ctx context.Context, hackId int, reqEditors ...RequestEditorFn) (*GetHacksHackIdResponse, error)

	// PostHacksHackIdEnterWithBodyWithResponse request with any body
	PostHacksHackIdEnterWithBodyWithResponse(ctx context.Context, hackId int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostHacksHackIdEnterResponse, error)

	PostHacksHackIdEnterWithResponse(ctx context.Context, hackId int, body PostHacksHackIdEnterJSONRequestBody, reqEditors ...RequestEditorFn) (*PostHacksHackIdEnterResponse, error)

	// GetHacksHackIdInvitationsWithResponse request
	GetHacksHackIdInvitationsWithResponse(ctx context.Context, hackId int, reqEditors ...RequestEditorFn) (*GetHacksHackIdInvitationsResponse, error)

	// GetHacksHackIdInvitationsInviteIdAcceptWithResponse request
	GetHacksHackIdInvitationsInviteIdAcceptWithResponse(ctx context.Context, hackId int, inviteId int, reqEditors ...RequestEditorFn) (*GetHacksHackIdInvitationsInviteIdAcceptResponse, error)

	// GetHacksHackIdParticipantsWithResponse request
	GetHacksHackIdParticipantsWithResponse(ctx context.Context, hackId int, reqEditors ...RequestEditorFn) (*GetHacksHackIdParticipantsResponse, error)

	// GetHacksHackIdParticipantsParticipantIdWithResponse request
	GetHacksHackIdParticipantsParticipantIdWithResponse(ctx context.Context, hackId int, participantId int, reqEditors ...RequestEditorFn) (*GetHacksHackIdParticipantsParticipantIdResponse, error)

	// PostHacksHackIdParticipantsParticipantsIdInviteWithResponse request
	PostHacksHackIdParticipantsParticipantsIdInviteWithResponse(ctx context.Context, hackId int, participantsId int, reqEditors ...RequestEditorFn) (*PostHacksHackIdParticipantsParticipantsIdInviteResponse, error)

	// GetHacksHackIdRequestsWithResponse request
	GetHacksHackIdRequestsWithResponse(ctx context.Context, hackId int, reqEditors ...RequestEditorFn) (*GetHacksHackIdRequestsResponse, error)

	// PostHacksHackIdRequestsRequestIdAcceptWithResponse request
	PostHacksHackIdRequestsRequestIdAcceptWithResponse(ctx context.Context, hackId int, requestId int, reqEditors ...RequestEditorFn) (*PostHacksHackIdRequestsRequestIdAcceptResponse, error)

	// GetHacksHackIdTeamsWithResponse request
	GetHacksHackIdTeamsWithResponse(ctx context.Context, hackId int, reqEditors ...RequestEditorFn) (*GetHacksHackIdTeamsResponse, error)

	// PostHacksHackIdTeamsWithBodyWithResponse request with any body
	PostHacksHackIdTeamsWithBodyWithResponse(ctx context.Context, hackId int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostHacksHackIdTeamsResponse, error)

	PostHacksHackIdTeamsWithResponse(ctx context.Context, hackId int, body PostHacksHackIdTeamsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostHacksHackIdTeamsResponse, error)

	// GetHacksHackIdTeamsTeamIdWithResponse request
	GetHacksHackIdTeamsTeamIdWithResponse(ctx context.Context, hackId int, teamId int, reqEditors ...RequestEditorFn) (*GetHacksHackIdTeamsTeamIdResponse, error)

	// PostHacksHackIdTeamsTeamIdRequestWithResponse request
	PostHacksHackIdTeamsTeamIdRequestWithResponse(ctx context.Context, hackId int, teamId int, reqEditors ...RequestEditorFn) (*PostHacksHackIdTeamsTeamIdRequestResponse, error)

	// PostLoginWithBodyWithResponse request with any body
	PostLoginWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostLoginResponse, error)

	PostLoginWithResponse(ctx context.Context, body PostLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*PostLoginResponse, error)

	// GetUsersUserIdWithResponse request
	GetUsersUserIdWithResponse(ctx context.Context, userId int, reqEditors ...RequestEditorFn) (*GetUsersUserIdResponse, error)

	// GetUsersUserIdTeamsWithResponse request
	GetUsersUserIdTeamsWithResponse(ctx context.Context, userId int, reqEditors ...RequestEditorFn) (*GetUsersUserIdTeamsResponse, error)
}

type PostAdminHacksResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostAdminHacksResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostAdminHacksResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostAdminLoginResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Token
}

// Status returns HTTPResponse.Status
func (r PostAdminLoginResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostAdminLoginResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHacksResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]HackathonShort
}

// Status returns HTTPResponse.Status
func (r GetHacksResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHacksResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHacksHackIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]HackathonPage
}

// Status returns HTTPResponse.Status
func (r GetHacksHackIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHacksHackIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostHacksHackIdEnterResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostHacksHackIdEnterResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostHacksHackIdEnterResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHacksHackIdInvitationsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Invite
}

// Status returns HTTPResponse.Status
func (r GetHacksHackIdInvitationsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHacksHackIdInvitationsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHacksHackIdInvitationsInviteIdAcceptResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetHacksHackIdInvitationsInviteIdAcceptResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHacksHackIdInvitationsInviteIdAcceptResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHacksHackIdParticipantsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Participant
}

// Status returns HTTPResponse.Status
func (r GetHacksHackIdParticipantsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHacksHackIdParticipantsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHacksHackIdParticipantsParticipantIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Participant
}

// Status returns HTTPResponse.Status
func (r GetHacksHackIdParticipantsParticipantIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHacksHackIdParticipantsParticipantIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostHacksHackIdParticipantsParticipantsIdInviteResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostHacksHackIdParticipantsParticipantsIdInviteResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostHacksHackIdParticipantsParticipantsIdInviteResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHacksHackIdRequestsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Request
}

// Status returns HTTPResponse.Status
func (r GetHacksHackIdRequestsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHacksHackIdRequestsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostHacksHackIdRequestsRequestIdAcceptResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostHacksHackIdRequestsRequestIdAcceptResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostHacksHackIdRequestsRequestIdAcceptResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHacksHackIdTeamsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Team
}

// Status returns HTTPResponse.Status
func (r GetHacksHackIdTeamsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHacksHackIdTeamsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostHacksHackIdTeamsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *[]Team
}

// Status returns HTTPResponse.Status
func (r PostHacksHackIdTeamsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostHacksHackIdTeamsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHacksHackIdTeamsTeamIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Team
}

// Status returns HTTPResponse.Status
func (r GetHacksHackIdTeamsTeamIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHacksHackIdTeamsTeamIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostHacksHackIdTeamsTeamIdRequestResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostHacksHackIdTeamsTeamIdRequestResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostHacksHackIdTeamsTeamIdRequestResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostLoginResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Token
}

// Status returns HTTPResponse.Status
func (r PostLoginResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostLoginResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetUsersUserIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *User
}

// Status returns HTTPResponse.Status
func (r GetUsersUserIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetUsersUserIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetUsersUserIdTeamsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]TeamShort
}

// Status returns HTTPResponse.Status
func (r GetUsersUserIdTeamsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetUsersUserIdTeamsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostAdminHacksWithBodyWithResponse request with arbitrary body returning *PostAdminHacksResponse
func (c *ClientWithResponses) PostAdminHacksWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAdminHacksResponse, error) {
	rsp, err := c.PostAdminHacksWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAdminHacksResponse(rsp)
}

func (c *ClientWithResponses) PostAdminHacksWithResponse(ctx context.Context, body PostAdminHacksJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAdminHacksResponse, error) {
	rsp, err := c.PostAdminHacks(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAdminHacksResponse(rsp)
}

// PostAdminLoginWithBodyWithResponse request with arbitrary body returning *PostAdminLoginResponse
func (c *ClientWithResponses) PostAdminLoginWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAdminLoginResponse, error) {
	rsp, err := c.PostAdminLoginWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAdminLoginResponse(rsp)
}

func (c *ClientWithResponses) PostAdminLoginWithResponse(ctx context.Context, body PostAdminLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAdminLoginResponse, error) {
	rsp, err := c.PostAdminLogin(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAdminLoginResponse(rsp)
}

// GetHacksWithResponse request returning *GetHacksResponse
func (c *ClientWithResponses) GetHacksWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHacksResponse, error) {
	rsp, err := c.GetHacks(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHacksResponse(rsp)
}

// GetHacksHackIdWithResponse request returning *GetHacksHackIdResponse
func (c *ClientWithResponses) GetHacksHackIdWithResponse(ctx context.Context, hackId int, reqEditors ...RequestEditorFn) (*GetHacksHackIdResponse, error) {
	rsp, err := c.GetHacksHackId(ctx, hackId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHacksHackIdResponse(rsp)
}

// PostHacksHackIdEnterWithBodyWithResponse request with arbitrary body returning *PostHacksHackIdEnterResponse
func (c *ClientWithResponses) PostHacksHackIdEnterWithBodyWithResponse(ctx context.Context, hackId int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostHacksHackIdEnterResponse, error) {
	rsp, err := c.PostHacksHackIdEnterWithBody(ctx, hackId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostHacksHackIdEnterResponse(rsp)
}

func (c *ClientWithResponses) PostHacksHackIdEnterWithResponse(ctx context.Context, hackId int, body PostHacksHackIdEnterJSONRequestBody, reqEditors ...RequestEditorFn) (*PostHacksHackIdEnterResponse, error) {
	rsp, err := c.PostHacksHackIdEnter(ctx, hackId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostHacksHackIdEnterResponse(rsp)
}

// GetHacksHackIdInvitationsWithResponse request returning *GetHacksHackIdInvitationsResponse
func (c *ClientWithResponses) GetHacksHackIdInvitationsWithResponse(ctx context.Context, hackId int, reqEditors ...RequestEditorFn) (*GetHacksHackIdInvitationsResponse, error) {
	rsp, err := c.GetHacksHackIdInvitations(ctx, hackId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHacksHackIdInvitationsResponse(rsp)
}

// GetHacksHackIdInvitationsInviteIdAcceptWithResponse request returning *GetHacksHackIdInvitationsInviteIdAcceptResponse
func (c *ClientWithResponses) GetHacksHackIdInvitationsInviteIdAcceptWithResponse(ctx context.Context, hackId int, inviteId int, reqEditors ...RequestEditorFn) (*GetHacksHackIdInvitationsInviteIdAcceptResponse, error) {
	rsp, err := c.GetHacksHackIdInvitationsInviteIdAccept(ctx, hackId, inviteId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHacksHackIdInvitationsInviteIdAcceptResponse(rsp)
}

// GetHacksHackIdParticipantsWithResponse request returning *GetHacksHackIdParticipantsResponse
func (c *ClientWithResponses) GetHacksHackIdParticipantsWithResponse(ctx context.Context, hackId int, reqEditors ...RequestEditorFn) (*GetHacksHackIdParticipantsResponse, error) {
	rsp, err := c.GetHacksHackIdParticipants(ctx, hackId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHacksHackIdParticipantsResponse(rsp)
}

// GetHacksHackIdParticipantsParticipantIdWithResponse request returning *GetHacksHackIdParticipantsParticipantIdResponse
func (c *ClientWithResponses) GetHacksHackIdParticipantsParticipantIdWithResponse(ctx context.Context, hackId int, participantId int, reqEditors ...RequestEditorFn) (*GetHacksHackIdParticipantsParticipantIdResponse, error) {
	rsp, err := c.GetHacksHackIdParticipantsParticipantId(ctx, hackId, participantId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHacksHackIdParticipantsParticipantIdResponse(rsp)
}

// PostHacksHackIdParticipantsParticipantsIdInviteWithResponse request returning *PostHacksHackIdParticipantsParticipantsIdInviteResponse
func (c *ClientWithResponses) PostHacksHackIdParticipantsParticipantsIdInviteWithResponse(ctx context.Context, hackId int, participantsId int, reqEditors ...RequestEditorFn) (*PostHacksHackIdParticipantsParticipantsIdInviteResponse, error) {
	rsp, err := c.PostHacksHackIdParticipantsParticipantsIdInvite(ctx, hackId, participantsId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostHacksHackIdParticipantsParticipantsIdInviteResponse(rsp)
}

// GetHacksHackIdRequestsWithResponse request returning *GetHacksHackIdRequestsResponse
func (c *ClientWithResponses) GetHacksHackIdRequestsWithResponse(ctx context.Context, hackId int, reqEditors ...RequestEditorFn) (*GetHacksHackIdRequestsResponse, error) {
	rsp, err := c.GetHacksHackIdRequests(ctx, hackId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHacksHackIdRequestsResponse(rsp)
}

// PostHacksHackIdRequestsRequestIdAcceptWithResponse request returning *PostHacksHackIdRequestsRequestIdAcceptResponse
func (c *ClientWithResponses) PostHacksHackIdRequestsRequestIdAcceptWithResponse(ctx context.Context, hackId int, requestId int, reqEditors ...RequestEditorFn) (*PostHacksHackIdRequestsRequestIdAcceptResponse, error) {
	rsp, err := c.PostHacksHackIdRequestsRequestIdAccept(ctx, hackId, requestId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostHacksHackIdRequestsRequestIdAcceptResponse(rsp)
}

// GetHacksHackIdTeamsWithResponse request returning *GetHacksHackIdTeamsResponse
func (c *ClientWithResponses) GetHacksHackIdTeamsWithResponse(ctx context.Context, hackId int, reqEditors ...RequestEditorFn) (*GetHacksHackIdTeamsResponse, error) {
	rsp, err := c.GetHacksHackIdTeams(ctx, hackId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHacksHackIdTeamsResponse(rsp)
}

// PostHacksHackIdTeamsWithBodyWithResponse request with arbitrary body returning *PostHacksHackIdTeamsResponse
func (c *ClientWithResponses) PostHacksHackIdTeamsWithBodyWithResponse(ctx context.Context, hackId int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostHacksHackIdTeamsResponse, error) {
	rsp, err := c.PostHacksHackIdTeamsWithBody(ctx, hackId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostHacksHackIdTeamsResponse(rsp)
}

func (c *ClientWithResponses) PostHacksHackIdTeamsWithResponse(ctx context.Context, hackId int, body PostHacksHackIdTeamsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostHacksHackIdTeamsResponse, error) {
	rsp, err := c.PostHacksHackIdTeams(ctx, hackId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostHacksHackIdTeamsResponse(rsp)
}

// GetHacksHackIdTeamsTeamIdWithResponse request returning *GetHacksHackIdTeamsTeamIdResponse
func (c *ClientWithResponses) GetHacksHackIdTeamsTeamIdWithResponse(ctx context.Context, hackId int, teamId int, reqEditors ...RequestEditorFn) (*GetHacksHackIdTeamsTeamIdResponse, error) {
	rsp, err := c.GetHacksHackIdTeamsTeamId(ctx, hackId, teamId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHacksHackIdTeamsTeamIdResponse(rsp)
}

// PostHacksHackIdTeamsTeamIdRequestWithResponse request returning *PostHacksHackIdTeamsTeamIdRequestResponse
func (c *ClientWithResponses) PostHacksHackIdTeamsTeamIdRequestWithResponse(ctx context.Context, hackId int, teamId int, reqEditors ...RequestEditorFn) (*PostHacksHackIdTeamsTeamIdRequestResponse, error) {
	rsp, err := c.PostHacksHackIdTeamsTeamIdRequest(ctx, hackId, teamId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostHacksHackIdTeamsTeamIdRequestResponse(rsp)
}

// PostLoginWithBodyWithResponse request with arbitrary body returning *PostLoginResponse
func (c *ClientWithResponses) PostLoginWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostLoginResponse, error) {
	rsp, err := c.PostLoginWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostLoginResponse(rsp)
}

func (c *ClientWithResponses) PostLoginWithResponse(ctx context.Context, body PostLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*PostLoginResponse, error) {
	rsp, err := c.PostLogin(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostLoginResponse(rsp)
}

// GetUsersUserIdWithResponse request returning *GetUsersUserIdResponse
func (c *ClientWithResponses) GetUsersUserIdWithResponse(ctx context.Context, userId int, reqEditors ...RequestEditorFn) (*GetUsersUserIdResponse, error) {
	rsp, err := c.GetUsersUserId(ctx, userId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetUsersUserIdResponse(rsp)
}

// GetUsersUserIdTeamsWithResponse request returning *GetUsersUserIdTeamsResponse
func (c *ClientWithResponses) GetUsersUserIdTeamsWithResponse(ctx context.Context, userId int, reqEditors ...RequestEditorFn) (*GetUsersUserIdTeamsResponse, error) {
	rsp, err := c.GetUsersUserIdTeams(ctx, userId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetUsersUserIdTeamsResponse(rsp)
}

// ParsePostAdminHacksResponse parses an HTTP response from a PostAdminHacksWithResponse call
func ParsePostAdminHacksResponse(rsp *http.Response) (*PostAdminHacksResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostAdminHacksResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParsePostAdminLoginResponse parses an HTTP response from a PostAdminLoginWithResponse call
func ParsePostAdminLoginResponse(rsp *http.Response) (*PostAdminLoginResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostAdminLoginResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Token
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetHacksResponse parses an HTTP response from a GetHacksWithResponse call
func ParseGetHacksResponse(rsp *http.Response) (*GetHacksResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHacksResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []HackathonShort
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetHacksHackIdResponse parses an HTTP response from a GetHacksHackIdWithResponse call
func ParseGetHacksHackIdResponse(rsp *http.Response) (*GetHacksHackIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHacksHackIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []HackathonPage
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostHacksHackIdEnterResponse parses an HTTP response from a PostHacksHackIdEnterWithResponse call
func ParsePostHacksHackIdEnterResponse(rsp *http.Response) (*PostHacksHackIdEnterResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostHacksHackIdEnterResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetHacksHackIdInvitationsResponse parses an HTTP response from a GetHacksHackIdInvitationsWithResponse call
func ParseGetHacksHackIdInvitationsResponse(rsp *http.Response) (*GetHacksHackIdInvitationsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHacksHackIdInvitationsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Invite
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetHacksHackIdInvitationsInviteIdAcceptResponse parses an HTTP response from a GetHacksHackIdInvitationsInviteIdAcceptWithResponse call
func ParseGetHacksHackIdInvitationsInviteIdAcceptResponse(rsp *http.Response) (*GetHacksHackIdInvitationsInviteIdAcceptResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHacksHackIdInvitationsInviteIdAcceptResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetHacksHackIdParticipantsResponse parses an HTTP response from a GetHacksHackIdParticipantsWithResponse call
func ParseGetHacksHackIdParticipantsResponse(rsp *http.Response) (*GetHacksHackIdParticipantsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHacksHackIdParticipantsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Participant
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetHacksHackIdParticipantsParticipantIdResponse parses an HTTP response from a GetHacksHackIdParticipantsParticipantIdWithResponse call
func ParseGetHacksHackIdParticipantsParticipantIdResponse(rsp *http.Response) (*GetHacksHackIdParticipantsParticipantIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHacksHackIdParticipantsParticipantIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Participant
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostHacksHackIdParticipantsParticipantsIdInviteResponse parses an HTTP response from a PostHacksHackIdParticipantsParticipantsIdInviteWithResponse call
func ParsePostHacksHackIdParticipantsParticipantsIdInviteResponse(rsp *http.Response) (*PostHacksHackIdParticipantsParticipantsIdInviteResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostHacksHackIdParticipantsParticipantsIdInviteResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetHacksHackIdRequestsResponse parses an HTTP response from a GetHacksHackIdRequestsWithResponse call
func ParseGetHacksHackIdRequestsResponse(rsp *http.Response) (*GetHacksHackIdRequestsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHacksHackIdRequestsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Request
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostHacksHackIdRequestsRequestIdAcceptResponse parses an HTTP response from a PostHacksHackIdRequestsRequestIdAcceptWithResponse call
func ParsePostHacksHackIdRequestsRequestIdAcceptResponse(rsp *http.Response) (*PostHacksHackIdRequestsRequestIdAcceptResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostHacksHackIdRequestsRequestIdAcceptResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetHacksHackIdTeamsResponse parses an HTTP response from a GetHacksHackIdTeamsWithResponse call
func ParseGetHacksHackIdTeamsResponse(rsp *http.Response) (*GetHacksHackIdTeamsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHacksHackIdTeamsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Team
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostHacksHackIdTeamsResponse parses an HTTP response from a PostHacksHackIdTeamsWithResponse call
func ParsePostHacksHackIdTeamsResponse(rsp *http.Response) (*PostHacksHackIdTeamsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostHacksHackIdTeamsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest []Team
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}

// ParseGetHacksHackIdTeamsTeamIdResponse parses an HTTP response from a GetHacksHackIdTeamsTeamIdWithResponse call
func ParseGetHacksHackIdTeamsTeamIdResponse(rsp *http.Response) (*GetHacksHackIdTeamsTeamIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHacksHackIdTeamsTeamIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Team
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostHacksHackIdTeamsTeamIdRequestResponse parses an HTTP response from a PostHacksHackIdTeamsTeamIdRequestWithResponse call
func ParsePostHacksHackIdTeamsTeamIdRequestResponse(rsp *http.Response) (*PostHacksHackIdTeamsTeamIdRequestResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostHacksHackIdTeamsTeamIdRequestResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParsePostLoginResponse parses an HTTP response from a PostLoginWithResponse call
func ParsePostLoginResponse(rsp *http.Response) (*PostLoginResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostLoginResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Token
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetUsersUserIdResponse parses an HTTP response from a GetUsersUserIdWithResponse call
func ParseGetUsersUserIdResponse(rsp *http.Response) (*GetUsersUserIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetUsersUserIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest User
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetUsersUserIdTeamsResponse parses an HTTP response from a GetUsersUserIdTeamsWithResponse call
func ParseGetUsersUserIdTeamsResponse(rsp *http.Response) (*GetUsersUserIdTeamsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetUsersUserIdTeamsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []TeamShort
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
