// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package client

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// AdminLogin defines model for AdminLogin.
type AdminLogin struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

// FormCreate defines model for FormCreate.
type FormCreate struct {
	AdditionalInfo string `json:"additional_info"`

	// Experience Количество хакатонов
	Experience int     `json:"experience"`
	Role       Role    `json:"role"`
	Skills     []Skill `json:"skills"`
}

// HackCreate defines model for HackCreate.
type HackCreate struct {
	Description string             `json:"description"`
	EndDate     openapi_types.Date `json:"end_date"`
	MaxTeamSize int                `json:"max_team_size"`
	Name        string             `json:"name"`
	Prize       int                `json:"prize"`
	StartDate   openapi_types.Date `json:"start_date"`
}

// HackathonPage defines model for HackathonPage.
type HackathonPage struct {
	Description string             `json:"description"`
	EndDate     openapi_types.Date `json:"end_date"`
	Id          int                `json:"id"`
	MaxTeamSize int                `json:"max_team_size"`
	Name        string             `json:"name"`
	Prize       int                `json:"prize"`
	StartDate   openapi_types.Date `json:"start_date"`
}

// HackathonShort defines model for HackathonShort.
type HackathonShort struct {
	Description string             `json:"description"`
	EndDate     openapi_types.Date `json:"end_date"`
	Id          int                `json:"id"`
	Name        string             `json:"name"`
	StartDate   openapi_types.Date `json:"start_date"`
}

// Health defines model for Health.
type Health struct {
	Resp string `json:"resp"`
}

// Invite defines model for Invite.
type Invite struct {
	Id          int          `json:"id"`
	Participant *Participant `json:"participant,omitempty"`
	TeamId      int          `json:"team_id"`
}

// Participant defines model for Participant.
type Participant struct {
	FirstName string  `json:"first_name"`
	Id        int     `json:"id"`
	LastName  string  `json:"last_name"`
	Role      Role    `json:"role"`
	Skills    []Skill `json:"skills"`
	TeamId    int     `json:"team_id"`
}

// Request defines model for Request.
type Request struct {
	Id     int `json:"id"`
	TeamId int `json:"team_id"`
}

// Role defines model for Role.
type Role struct {
	Id   int    `json:"id"`
	Name string `json:"name"`
}

// Skill defines model for Skill.
type Skill struct {
	Id   int    `json:"id"`
	Name string `json:"name"`
}

// Team defines model for Team.
type Team struct {
	CaptainId int           `json:"captain_id"`
	Id        int           `json:"id"`
	MaxSize   int           `json:"max_size"`
	Members   []Participant `json:"members"`
	Name      string        `json:"name"`
}

// TeamCreate defines model for TeamCreate.
type TeamCreate struct {
	CaptainId int    `json:"captain_id"`
	Name      string `json:"name"`
}

// TeamShort defines model for TeamShort.
type TeamShort struct {
	HackId   int    `json:"hack_id"`
	HackName string `json:"hack_name"`
	Id       int    `json:"id"`
	MaxSize  int    `json:"max_size"`
	Name     string `json:"name"`
}

// Token defines model for Token.
type Token struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

// User defines model for User.
type User struct {
	Bio       string `json:"bio"`
	FirstName string `json:"first_name"`
	Id        int64  `json:"id"`
	IsAdmin   bool   `json:"is_admin"`
	LastName  string `json:"last_name"`
	Login     string `json:"login"`
}

// UserLogin defines model for UserLogin.
type UserLogin struct {
	Code string `json:"code"`
}

// PostApiAdminHacksJSONRequestBody defines body for PostApiAdminHacks for application/json ContentType.
type PostApiAdminHacksJSONRequestBody = HackCreate

// PostApiAdminLoginJSONRequestBody defines body for PostApiAdminLogin for application/json ContentType.
type PostApiAdminLoginJSONRequestBody = AdminLogin

// PostApiHacksHackIdEnterJSONRequestBody defines body for PostApiHacksHackIdEnter for application/json ContentType.
type PostApiHacksHackIdEnterJSONRequestBody = FormCreate

// PostApiHacksHackIdTeamsJSONRequestBody defines body for PostApiHacksHackIdTeams for application/json ContentType.
type PostApiHacksHackIdTeamsJSONRequestBody = TeamCreate

// PostApiLoginJSONRequestBody defines body for PostApiLogin for application/json ContentType.
type PostApiLoginJSONRequestBody = UserLogin
