// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package client

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// AdminLogin defines model for AdminLogin.
type AdminLogin struct {
	Login    *string `json:"login,omitempty"`
	Password *string `json:"password,omitempty"`
}

// FormCreate defines model for FormCreate.
type FormCreate struct {
	AdditionalInfo *string `json:"additional_info,omitempty"`

	// Experience Количество хакатонов
	Experience *int     `json:"experience,omitempty"`
	Role       *Role    `json:"role,omitempty"`
	Skills     *[]Skill `json:"skills,omitempty"`
}

// HackCreate defines model for HackCreate.
type HackCreate struct {
	Description *string             `json:"description,omitempty"`
	EndDate     *openapi_types.Date `json:"end_date,omitempty"`
	MaxTeamSize *int                `json:"max_team_size,omitempty"`
	Name        *string             `json:"name,omitempty"`
	Prize       *int                `json:"prize,omitempty"`
	StartDate   *openapi_types.Date `json:"start_date,omitempty"`
}

// HackathonPage defines model for HackathonPage.
type HackathonPage struct {
	Description *string             `json:"description,omitempty"`
	EndDate     *openapi_types.Date `json:"end_date,omitempty"`
	Id          *int                `json:"id,omitempty"`
	MaxTeamSize *int                `json:"max_team_size,omitempty"`
	Name        *string             `json:"name,omitempty"`
	Prize       *int                `json:"prize,omitempty"`
	StartDate   *openapi_types.Date `json:"start_date,omitempty"`
}

// HackathonShort defines model for HackathonShort.
type HackathonShort struct {
	Description *string             `json:"description,omitempty"`
	EndDate     *openapi_types.Date `json:"end_date,omitempty"`
	Id          *int                `json:"id,omitempty"`
	Name        *string             `json:"name,omitempty"`
	StartDate   *openapi_types.Date `json:"start_date,omitempty"`
}

// Invite defines model for Invite.
type Invite struct {
	Id            *int `json:"id,omitempty"`
	ParticipantId *int `json:"participant_id,omitempty"`
	TeamId        *int `json:"team_id,omitempty"`
}

// Participant defines model for Participant.
type Participant struct {
	FirstName *string   `json:"first_name,omitempty"`
	Id        *int      `json:"id,omitempty"`
	LastName  *string   `json:"last_name,omitempty"`
	Roles     *[]string `json:"roles,omitempty"`
	TeamId    *int      `json:"team_id,omitempty"`
}

// Request defines model for Request.
type Request struct {
	Id     *int `json:"id,omitempty"`
	TeamId *int `json:"team_id,omitempty"`
}

// Role defines model for Role.
type Role struct {
	Id   *int    `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// Skill defines model for Skill.
type Skill struct {
	Id   *int    `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// Team defines model for Team.
type Team struct {
	Id      *int    `json:"id,omitempty"`
	MaxSize *int    `json:"max_size,omitempty"`
	Members *[]User `json:"members,omitempty"`
	Name    *string `json:"name,omitempty"`
}

// TeamCreate defines model for TeamCreate.
type TeamCreate struct {
	CaptainId *int    `json:"captain_id,omitempty"`
	Name      *string `json:"name,omitempty"`
}

// TeamShort defines model for TeamShort.
type TeamShort struct {
	HackId   *int    `json:"hack_id,omitempty"`
	HackName *string `json:"hack_name,omitempty"`
	Id       *int    `json:"id,omitempty"`
	MaxSize  *int    `json:"max_size,omitempty"`
	Name     *string `json:"name,omitempty"`
}

// Token defines model for Token.
type Token struct {
	AccessToken  *string `json:"access_token,omitempty"`
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// User defines model for User.
type User struct {
	Bio       *string `json:"bio,omitempty"`
	FirstName *string `json:"first_name,omitempty"`
	Id        *int    `json:"id,omitempty"`
	LastName  *string `json:"last_name,omitempty"`
}

// UserLogin defines model for UserLogin.
type UserLogin struct {
	Code *string `json:"code,omitempty"`
}

// PostAdminHacksJSONRequestBody defines body for PostAdminHacks for application/json ContentType.
type PostAdminHacksJSONRequestBody = HackCreate

// PostAdminLoginJSONRequestBody defines body for PostAdminLogin for application/json ContentType.
type PostAdminLoginJSONRequestBody = AdminLogin

// PostHacksHackIdEnterJSONRequestBody defines body for PostHacksHackIdEnter for application/json ContentType.
type PostHacksHackIdEnterJSONRequestBody = FormCreate

// PostHacksHackIdTeamsJSONRequestBody defines body for PostHacksHackIdTeams for application/json ContentType.
type PostHacksHackIdTeamsJSONRequestBody = TeamCreate

// PostLoginJSONRequestBody defines body for PostLogin for application/json ContentType.
type PostLoginJSONRequestBody = UserLogin
